version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Crear entorno virtual e instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas con cobertura
          command: |
            . venv/bin/activate
            coverage run -m pytest
      - run:
          name: Generar reporte HTML
          command: |
            . venv/bin/activate
            coverage html
      - store_artifacts:
          path: htmlcov
          destination: coverage-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
