version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    parallelism: 2  # Se ejecutará en 2 contenedores paralelos
    steps:
      - checkout
      - run:
          name: Crear entorno virtual e instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            . venv/bin/activate
            circleci tests glob "tests/test_*.py" | circleci tests split | xargs -n 1 pytest

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
