version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  crear-entorno:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Crear entorno virtual e instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - .

  pruebas:
    docker:
      - image: cimg/python:3.12
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar pruebas con coverage
          command: |
            . venv/bin/activate
            coverage run --source=. -m pytest
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
      - store_artifacts:
          path: .coverage
          destination: coverage-data
      - slack/notify:
          event: fail
          channel: "#estudiante"
          custom: |
            {
              "text": ":x: *Pruebas Fallidas* en `calculadora-proyecto` (rama: `<< pipeline.git.branch >>`)"
            }
      - slack/notify:
          event: pass
          channel: "#estudiante"
          custom: |
            {
              "text": ":white_check_mark: *Pruebas exitosas* en `calculadora-proyecto` (rama: `<< pipeline.git.branch >>`)"
            }

  cobertura-html:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generar reporte HTML de cobertura
          command: |
            . venv/bin/activate
            coverage html --ignore-errors
      - store_artifacts:
          path: htmlcov
          destination: coverage-report
      - slack/notify:
          event: always
          channel: "#general-procesosdesoftware"
          custom: |
            {
              "text": ":bar_chart: Se ha generado el *reporte HTML de cobertura* en `calculadora-proyecto`."
            }

  analisis-flake8:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar análisis de código con flake8
          command: |
            . venv/bin/activate
            pip install flake8
            flake8 . --exit-zero
      - slack/notify:
          event: always
          channel: "#general-procesosdesoftware"
          custom: |
            {
              "text": ":mag: *flake8 ejecutado* en `calculadora-proyecto`. Revisa posibles advertencias o errores de formato."
            }

  reporte-cobertura-terminal:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Mostrar resumen de cobertura en consola
          command: |
            . venv/bin/activate
            coverage report
      - slack/notify:
          event: always
          channel: "#general-procesosdesoftware"
          custom: |
            {
              "text": ":scroll: *Resumen de cobertura impreso en terminal* para `calculadora-proyecto`."
            }

  exportar-coverage-raw:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: .coverage
          destination: raw-coverage
      - slack/notify:
          event: always
          channel: "#general-procesosdesoftware"
          custom: |
            {
              "text": ":inbox_tray: *Archivo `.coverage` exportado como artifact* desde `calculadora-proyecto`."
            }

  verificar-funciones-principales:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Buscar funciones __main__
          command: |
            grep -r "__main__" calculadora || echo "No se encontró ninguna entrada con if __name__ == '__main__'"
      - slack/notify:
          event: always
          channel: "#estudiante"
          custom: |
            {
              "text": ":bookmark_tabs: Se verificaron entradas `__main__` en los scripts de `calculadora-proyecto`."
            }

  verificar-archivos-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Validar existencia de archivos test
          command: |
            find calculadora -name '*.py' | while read file; do
              base=$(basename "$file" .py)
              test_file="tests/test_${base}.py"
              if [ ! -f "$test_file" ]; then
                echo "⚠️ Falta test para $file"
              fi
            done
      - slack/notify:
          event: always
          channel: "#estudiante"
          custom: |
            {
              "text": ":microscope: Se revisó correspondencia entre módulos y archivos de test en `calculadora-proyecto`."
            }

workflows:
  version: 2
  workflow-paralelo:
    jobs:
      - crear-entorno
      - pruebas:
          requires:
            - crear-entorno
      - cobertura-html:
          requires:
            - crear-entorno
      - analisis-flake8:
          requires:
            - crear-entorno
      - reporte-cobertura-terminal:
          requires:
            - crear-entorno
      - exportar-coverage-raw:
          requires:
            - crear-entorno
      - verificar-funciones-principales:
          requires:
            - crear-entorno
      - verificar-archivos-test:
          requires:
            - crear-entorno
